library version of people tracker
clearpathrobotics/people pull request #1
Opened 2017-06-14 19:08 UTC by asaini89

2017-06-14 20:45 UTC, efernandez requested changes
Can we split on a PR for OpenCV3 support and other changes, AND another one that moves files and simply create the library, please?

2017-06-14 21:11 UTC, efernandez commented on leg_detector/src/leg_detector.cpp
>  static string fixed_frame              = "odom_combined";
`static string fixed_frame              = "odom";` for consistency with the change on the dynamic param file

2017-06-14 21:12 UTC, efernandez requested changes

2017-06-14 21:12 UTC, efernandez commented on leg_detector/src/leg_detector.cpp
> +    laser_sub_(nh_, "front/scan", 10),
I'd remap this from outside

2017-06-14 21:14 UTC, efernandez commented on leg_detector/src/leg_detector.cpp
>  static string fixed_frame              = "odom_combined";
Also, the change in `max_meas_jump_m` show be reflected in a commit, not "hidden" under a single commit :smiley:

2017-06-16 16:59 UTC, efernandez requested changes

2017-06-16 16:59 UTC, efernandez commented on leg_detector/include/leg_detector/leg_detector_lib.h
> +using namespace std;
You shouldn't do this on a header. Remove all and use them explicitly below.

2017-06-16 16:59 UTC, efernandez commented on leg_detector/include/leg_detector/matched_feature.h
> +using namespace laser_processor;
same as before

2017-06-16 16:59 UTC, efernandez commented on leg_detector/include/leg_detector/saved_feature.h
> +using namespace std;
same

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector.cpp
> +static double max_meas_jump_m          = 1.0;
Why did you change this?

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector.cpp
> +      float probability = 0.5 - forest->predict(tmp_mat, cv::noArray(), cv::ml::RTrees::PREDICT_SUM) / forest->getRoots().size();
Can `forest->getRoots().size()` be `0`? Then check for it, and set `probability = 0` in that case.

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +  double LegDetector::distance(list<SavedFeature*>::iterator it1,  list<SavedFeature*>::iterator it2)
`double LegDetector::distance(list<SavedFeature*>::iterator it1,  list<SavedFeature*>::iterator it2) const`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +    return sqrt(dx * dx + dy * dy + dz * dz);
optimization, provide a `distance2` version w/o the `sqrt`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +    Stamped<Point> one = (*it1)->position_, two = (*it2)->position_;
You can use `const Stamped<Point>` and also `const double`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +            && (d < closest_dist))
and here, if you use `distance2`, you can compare `d < closest_dist2`, where `closest_dist2 = closest_dist * closest_dist`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +        double dist_between_legs = distance(leg1, leg2);
same as before

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +          double d = distance(leg1, leg2);
same

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +        (*best1)->object_id = std::string(id);
With c++11 you can do `"Person" + std::to_string(next_p_id_++)`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +        saved_features_.erase(sf_iter++);
I think this should be `sf_iter = saved_features_.erase(sf_iter);`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +        delete(*sf_iter);
Use a `list<std::shared_ptr<SavedFeature>>` instead

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +    for (list<SavedFeature*>::iterator sf_iter = saved_features_.begin();
``` c++
for (auto& sf : saved_features_)
{
  sf->propagate(scan.header.stamp);
  propagated.push_back(sf);
}
```

And the same (use for-range loop), when possible, for other places

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +      float probability = 0.5 - forest->predict(tmp_mat, cv::noArray(), cv::ml::RTrees::PREDICT_SUM) / forest->getRoots().size();
Same re. `forest->getRoots().size() == 0` (actually check for `.empty()`)

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +      float probability = 0.5 - forest->predict(tmp_mat, cv::noArray(), cv::ml::RTrees::PREDICT_SUM) / forest->getRoots().size();
`const auto probability = forest->getRoots().empty() ? 0 : 0.5 - forest->predict(tmp_mat, cv::noArray(), cv::ml::RTrees::PREDICT_SUM) / forest->getRoots().size();`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +    for (list<SampleSet*>::iterator i = processor.getClusters().begin();
Like here: for-range loop

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +        if (dist < closest_dist)
Same for `distance2`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +        list<SavedFeature*>::iterator new_saved = saved_features_.insert(saved_features_.end(), new SavedFeature(loc, tfl, fixed_frame_, use_filter_, kal_p_, kal_q_, kal_r_));
Same for using `std::shared_ptr`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/leg_detector_lib.cpp
> +    while (matches.size() > 0)
`while (!matches.empty())`

2017-06-16 16:59 UTC, efernandez commented on leg_detector/src/saved_feature.cpp
> +    id_ = std::string(id);
Same for using `std::to_string`

2017-06-23 20:34 UTC, asaini89 commented on leg_detector/src/leg_detector.cpp
>  static string fixed_frame              = "odom_combined";
Changed to "odom".

Reverted the change to max_meas_jump.

This file is anyways not being used for our purposes.

2017-06-23 20:51 UTC, asaini89 commented on leg_detector/src/leg_detector.cpp
> +static double max_meas_jump_m          = 1.0;
Reverting it back, it was a test I was doing

2017-06-23 21:11 UTC, asaini89 commented on leg_detector/src/leg_detector.cpp
> +      float probability = 0.5 - forest->predict(tmp_mat, cv::noArray(), cv::ml::RTrees::PREDICT_SUM) / forest->getRoots().size();
No, that is read from trained model, if your roots are zero, most likely model file is missing

2017-06-26 17:16 UTC, asaini89 commented on leg_detector/src/leg_detector_lib.cpp
> +      float probability = 0.5 - forest->predict(tmp_mat, cv::noArray(), cv::ml::RTrees::PREDICT_SUM) / forest->getRoots().size();
getRoots cannot be zero because if it is, in that learned model is messed up which makes this anyways unusable.

2017-06-26 17:52 UTC, asaini89 commented on leg_detector/src/saved_feature.cpp
> +    id_ = std::string(id);
Done

2017-06-26 17:52 UTC, asaini89 commented on leg_detector/src/leg_detector_lib.cpp
> +    while (matches.size() > 0)
Done

2017-06-26 17:52 UTC, asaini89 commented on leg_detector/src/leg_detector_lib.cpp
> +        delete(*sf_iter);
Done

2017-06-27 03:43 UTC, efernandez approved these changes
:+1:

2017-06-27 17:18 UTC, merged

2017-06-27 17:22 UTC, afakihcpr commented on leg_detector/include/leg_detector/leg_detector_lib.h
> +  double distance(std::list<std::shared_ptr<SavedFeature>>::iterator it1,  std::list<std::shared_ptr<SavedFeature>>::iterator it2) const;
Make `std::list<std::shared_ptr<SavedFeature>>` a type